import ManagerTemplate from "@/components/adminTemplate";
import MenuList from "../userList";
import { ToastContainer } from "react-toastify";
export const metadata = {
  title: "User | KurbanQ Admin",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="User" id="user" userList={MenuList}>
      {children}
      <ToastContainer containerId={`toastUser`} />
    </ManagerTemplate>
  );
};
export default RootLayout;
