import ManagerTemplate from "@/components/adminTemplate";
import MenuList from "../userList";
export const metadata = {
  title: "Dashboard | KurbanQ Admin",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="Dashboard" id="Dashboard" userList={MenuList}>
      {children}
    </ManagerTemplate>
  );
};
export default RootLayout;
